- name: Pre-Install | Set local fact (default)
  set_fact:
    mkfs_storage_device: false
    configure_permissions: false

- name: Pre-Install | Set local fact (mkfs_storage_device=true)
  when: podman_containers_storage_device != None
  set_fact: mkfs_storage_device=true

- name: Pre-Install | Set local fact (configure_permissions=true)
  when: podman_users | length > 0 or podman_groups | length > 0
  set_fact: configure_permissions=true

- name: Pre-Install | Test {{ podman_containers_storage_device }}
  when: mkfs_storage_device | lower == 'true'
  command: test -e {{ podman_containers_storage_device }}
