---

- name: Pre-Install | Set local fact (default)
  set_fact:
    mkfs_storage_device: false
    configure_permissions: false

- name: Pre-Install | APT-based
  when: ansible_os_family | lower == 'debian'
  block:
      # Procedure from https://podman.io/getting-started/installation
    - name: Pre-Install | Add PPA repo
      shell: >
        source /etc/os-release ; \
        echo 'deb {{ podman_repo_apt_url }} /' \
        > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list" ; \
        \
        curl -L {{ podman_repo_key }} | sudo apt-key add -
      environment:
         https_proxy: "{{ pdoman_https_proxy }}"
         http_proxy: "{{ pdoman_http_proxy }}"
         no_proxy: "{{ podman_http_no_proxy }}"

- name: Pre-Install | RPM-based
  when: ansible_os_family | lower == 'redhat'
  block:
    - name: Pre-Install | Enable subscription to {{ podman_repo_name }}
      command: subscription-manager repos --enable="{{ podman_repo_name }}"

- name: Pre-Install | Set local fact (mkfs_storage_device=true)
  when: podman_containers_storage_device != None
  set_fact: mkfs_storage_device=true

- name: Pre-Install | Set local fact (configure_permissions=true)
  when: podman_users | length > 0 or podman_groups | length > 0
  set_fact: configure_permissions=true

- name: Pre-Install | Test {{ podman_containers_storage_device }}
  when: mkfs_storage_device | lower == 'true'
  command: test -e {{ podman_containers_storage_device }}
