---

- name: Pre-Install | Set local fact (default)
  set_fact:
    mkfs_storage_device: false
    configure_permissions: false

- name: Pre-Install | APT-based
  when: ansible_os_family | lower == 'debian'
  block:
    - name: Touch /etc/apt/sources.list
      file: path=/etc/apt/sources.list state=file

    - name: Pre-Install | Add PPA repo
      #apt_repository: repo="{{ podman_repo_apt_url }}"
      command: add-apt-repository --yes "{{ podman_repo_apt_url }}"

- name: Pre-Install | RPM-based
  when: ansible_os_family | lower == 'redhat'
  block:
    - name: Pre-Install | Enable subscription to {{ podman_repo_name }}
      command: subscription-manager repos --enable="{{ podman_repo_name }}"

- name: Pre-Install | Set local fact (mkfs_storage_device=true)
  when: podman_containers_storage_device != None
  set_fact: mkfs_storage_device=true

- name: Pre-Install | Set local fact (configure_permissions=true)
  when: podman_users | length > 0 or podman_groups | length > 0
  set_fact: configure_permissions=true

- name: Pre-Install | Test {{ podman_containers_storage_device }}
  when: mkfs_storage_device | lower == 'true'
  command: test -e {{ podman_containers_storage_device }}
