- name: Install | Install podman packages
  package:
    name: '{{ podman_distro_packages }}'
    state: '{{ podman_package_state }}'
    update_cache: "{{ (ansible_pkg_mgr == 'apt') | ternary('yes', omit) }}"
    cache_valid_time: "{{ (ansible_pkg_mgr == 'apt') | ternary(cache_timeout, omit) }}"
  register: install_packages
  until: install_packages is success
  retries: 5
  delay: 2
  tags:
  - install-apt
  - install-yum
  - install-zypper
